// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI migrations always target local SQLite. Runtime Turso settings
    // are resolved separately in src/lib/database-config.ts.
    url:
      process.env.LOCAL_DATABASE_URL ??
      process.env.DATABASE_URL ??
      "file:./dev.db",
  },
});
